#!/usr/bin/env python3
"""Generate ABI-NOTES.md from the runtime source.

The table is GENERATED, never hand-edited, because a hand-maintained status
column is wrong the moment someone implements a stub and forgets the doc --
and a capability table nobody trusts is worse than none, since the whole point
is to tell a caller what will happen before they call.

Status is read out of the source itself:

  VR_STUB_ERR(name)     -> error        refuses with a defined message
  VR_STUB_VOID(name)    -> silent-noop  DOES NOTHING and reports success
  VR_STUB_ZERO(name, T) -> silent-zero  returns 0 and reports success
  extern "C" ... { }    -> implemented, unless the preceding comment block
                           carries an `ABI-STATUS:` marker

The two silent kinds are called out separately from the erroring kind on
purpose. An entry point that refuses is a bug report; one that silently
succeeds with a wrong answer is a debugging session somewhere else entirely.

Run tools/check-abi-table.sh to fail a build when the file has drifted.
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ["AppleGPURT.cpp", "AppleGPUMetal.cpp"]

STATUS_ORDER = ["implemented", "sync-fallback", "silent-noop", "silent-zero",
                "error"]
STATUS_BLURB = {
    "implemented":   "real implementation",
    "sync-fallback": "works, but with bring-up semantics (see note)",
    "silent-noop":   "**does nothing and reports success**",
    "silent-zero":   "**returns 0 and reports success**",
    "error":         "refuses with a defined error",
}


def classify(path):
    """Yield (symbol, status, note, file, line)."""
    text = path.read_text()
    lines = text.split("\n")
    for i, line in enumerate(lines):
        m = re.match(r"VR_STUB_(ERR|VOID|ZERO)\((\w+)", line)
        if m:
            kind = {"ERR": "error", "VOID": "silent-noop",
                    "ZERO": "silent-zero"}[m.group(1)]
            yield m.group(2), kind, marker_note(lines, i), path.name, i + 1
            continue
        # `extern "C" <type> name(` on one line, or the type on its own line.
        m = re.match(r'extern "C"\s+.*?\b(AsyncRT_\w+|AppleGPU\w+)\s*\(', line)
        if not m and line.startswith('extern "C"') and i + 1 < len(lines):
            m = re.match(r"\s*(AsyncRT_\w+|AppleGPU\w+)\s*\(", lines[i + 1])
        if m:
            status, note = "implemented", marker_note(lines, i)
            if note and note.startswith("sync-fallback"):
                status, note = "sync-fallback", note[len("sync-fallback"):].lstrip(" -—")
            yield m.group(1), status, note, path.name, i + 1


def marker_note(lines, idx):
    """An `ABI-STATUS:` marker in the comment block above `idx`, if any."""
    j = idx - 1
    while j >= 0 and (lines[j].lstrip().startswith("//") or not lines[j].strip()):
        m = re.search(r"ABI-STATUS:\s*(.+)", lines[j])
        if m:
            return m.group(1).strip()
        if not lines[j].strip():
            break
        j -= 1
    return ""


def coverage():
    """Measured references from pre-link objects, if a snapshot exists.

    Kept in a checked-in TSV rather than measured live, so the table stays
    deterministic and the drift check stays meaningful on a machine that has
    not built the tests. Refresh with tools/measure-abi-coverage.sh.
    """
    p = ROOT / "ABI-COVERAGE.tsv"
    if not p.exists():
        return None, 0
    counts, objs = {}, 0
    for line in p.read_text().split("\n"):
        if line.startswith("# measured over"):
            objs = int(line.split()[3])
        if not line or line.startswith("#"):
            continue
        sym, _, n = line.partition("\t")
        counts[sym] = int(n)
    return counts, objs


def main():
    entries = {}
    for name in SOURCES:
        p = ROOT / name
        if not p.exists():
            sys.exit(f"missing source: {p}")
        for sym, status, note, f, ln in classify(p):
            # A real definition always wins over a stub of the same name.
            prev = entries.get(sym)
            if prev and STATUS_ORDER.index(prev[0]) <= STATUS_ORDER.index(status):
                continue
            entries[sym] = (status, note, f, ln)

    counts = {s: 0 for s in STATUS_ORDER}
    for status, _, _, _ in entries.values():
        counts[status] += 1

    cov, nobjs = coverage()
    rev = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                         capture_output=True, text=True).stdout.strip()

    out = []
    w = out.append
    w("# AsyncRT ABI capability table")
    w("")
    w("**Generated by `tools/gen-abi-table.py` from the runtime source. Do not")
    w("hand-edit** -- run the generator, or `tools/check-abi-table.sh` to see")
    w("what has drifted.")
    w("")
    w(f"Source: `{'`, `'.join(SOURCES)}` at `{rev}`.")
    w("")
    w("Status is read out of the code, not asserted here, because a")
    w("hand-maintained status column is wrong the moment someone implements a")
    w("stub and forgets the doc. A capability table nobody trusts is worse than")
    w("none: the entire point is to say what will happen *before* you call.")
    w("")
    w("| status | meaning | count |")
    w("|---|---|---|")
    for s in STATUS_ORDER:
        w(f"| `{s}` | {STATUS_BLURB[s]} | {counts[s]} |")
    w("")
    if cov is not None:
        reached = sum(1 for k in entries if cov.get(k, 0))
        w(f"Of {len(entries)} symbols, **{reached} are referenced by the built "
          f"tests and {len(entries) - reached} are not**, measured across "
          f"{nobjs} pre-link objects.")
        w("")
        w("That measurement has to come from the PRE-LINK objects. The runtime")
        w("is `alwayslink = True`, so every symbol is defined text in every")
        w("executable whether or not anything calls it, and `nm` on a linked")
        w("binary reports complete coverage of everything. The `tests` column")
        w("below counts objects whose UNDEFINED set names the symbol.")
        w("")
        w("It is static reachability, so a count is an upper bound: `>= 1`")
        w("means linked against, not executed. A `0` means genuinely never")
        w("referenced, and that direction is sound.")
        w("")
    w("## Read this first")
    w("")
    w("`silent-noop` and `silent-zero` are separated from `error` deliberately.")
    w("An entry point that refuses produces a bug report naming itself. One that")
    w("silently succeeds with a wrong answer produces a debugging session")
    w("somewhere else entirely, usually in a kernel, usually much later. They")
    w("are the same amount of \"not implemented\" and very different amounts of")
    w("trouble.")
    w("")
    w("Symbol parity -- every name Mojo `external_call`s being defined here --")
    w("is checked by `tools/check-abi-symbols.py`. It is a script rather than a")
    w("bazel test because the scan crosses the whole Mojo tree, which is not a")
    w("dependency a test target can express honestly. Run it in CI. It exists")
    w("because a truncated stub name sat undetected: the runtime defined")
    w("`AsyncRT_cuda_tensorMapEncodeIm` while Mojo called")
    w("`...EncodeIm2col`, a link failure waiting for the first build to reach")
    w("that path, and the table listed the misspelling as though it were")
    w("coverage.")
    w("")
    w("`error` entries abort callers that do not expect failure. `sync_parallelize`")
    w("calls `abort()` rather than propagating, so a stub there became a hard")
    w("process abort with no located diagnostic until it was implemented.")
    w("")
    for s in STATUS_ORDER:
        rows = sorted((k, v) for k, v in entries.items() if v[0] == s)
        if not rows:
            continue
        w(f"## {s} ({len(rows)})")
        w("")
        head = "| symbol | where | tests | note |" if cov is not None \
            else "| symbol | where | note |"
        w(head)
        w("|---|---|---|---|" if cov is not None else "|---|---|---|")
        for sym, (_, note, f, ln) in rows:
            if cov is None:
                w(f"| `{sym}` | {f}:{ln} | {note} |")
            else:
                n = cov.get(sym, 0)
                w(f"| `{sym}` | {f}:{ln} | {n if n else '**0**'} | {note} |")
        w("")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    sys.stdout.write(main())
